#!/bin/bash
### BEGIN INIT INFO
# Provides:          easyminer-preprocessing
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Easyminer preprocessing rest
# Description:       Easyminer preprocessing rest
### END INIT INFO


set -e

start() {
        echo "Starting easyminer preprocessing rest service..."
        start-stop-daemon --start --make-pidfile --pidfile /var/run/easyminer-preprocessing.pid --background --exec /root/easyminer-preprocessing/run
}

stop() {
        echo "Stopping easyminer preprocessing rest service..."
        /root/easyminer-preprocessing/stop
        start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/easyminer-preprocessing.pid
}

#
# main()
#

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload}"
        exit 1
esac
exit 0
