/*initialize ~= { _ => {
  System.setProperty("HADOOP_USER_NAME", "easyminer")
  System.setProperty("TEST_DB_SERVER", "192.168.137.128")
  System.setProperty("TEST_DB_USER", "easyminer")
  System.setProperty("TEST_DB_PASSWORD", "12345")
  System.setProperty("TEST_DB_NAME", "easyminer")
  System.setProperty("TEST_HIVE_SERVER", "sandbox.vse.cz")
  System.setProperty("TEST_HIVE_USER", "easyminer")
  System.setProperty("TEST_HIVE_PORT", "10000")
  System.setProperty("TEST_HIVE_NAME", "easyminer")
  System.setProperty("EM_USER_ENDPOINT", "http://localhost:8889/mockup")
  System.setProperty("EM_HADOOP_CONFIG_PATH", "sandbox-conf.xml")
  System.setProperty("EM_DCH_MYSQL_SERVER", "192.168.137.128")
  System.setProperty("EM_DCH_MYSQL_USER", "easyminer")
  System.setProperty("EM_DCH_MYSQL_PASSWORD", "12345")
  System.setProperty("EM_DCH_MYSQL_DB", "easyminer")
  System.setProperty("easyminer.user.auth-path", "/api/auth.json")
  System.setProperty("easyminer.user.limited-db-path", "/api/databases/mysql.json")
  System.setProperty("easyminer.user.unlimited-db-path", "/api/databases/hive.json")
}
}*/