install.packages("rJava", repos='http://cran.us.r-project.org')
install.packages("devtools", repos='http://cran.us.r-project.org')
install.packages("RJDBC", repos='http://cran.us.r-project.org')
install.packages("Rserve", repos='http://cran.us.r-project.org')
install.packages("RSclient", repos='http://cran.us.r-project.org')
install.packages("arules", repos='http://cran.us.r-project.org')
install.packages("R.utils", repos='http://cran.us.r-project.org')
library("devtools")
devtools::install_github("jaroslav-kuchar/rCBA")